<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event Feedback Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
            background-color: #f4f4f4;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .header img {
            width: 100px; /* Adjust the logo size */
            height: auto;
        }

        .header h2 {
            margin: 10px 0;
            color: #333;
        }

        .header p {
            color: #555;
            font-size: 14px;
        }

        h1 {
            text-align: center;
            color: rgb(0, 0, 0);
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            padding: 12px 15px;
            text-align: left;
            border: 1px solid #ddd;
        }

        th {
            background-color: rgb(197, 197, 197);
            color: white;
        }

        td {
            background-color: #ffffff;
        }

        tr:nth-child(even) td {
            background-color: #f9f9f9;
        }

        .table-container {
            margin-top: 30px;
        }

        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 14px;
            color: #888;
        }

        .date {
            text-align: right;
            font-size: 12px;
            color: #555;
            margin-top: -10px;
        }
    </style>
</head>
<body>

    <!-- Header Section with Logo, Church Name, and Date -->
    <div class="header">
    <img src="{{ asset('storage/event_images/logo.png') }}" alt="Church Logo">
        <h2>Church Name</h2>
        <p>Church Address or Tagline (optional)</p>
        <p class="date">Date: {{ \Carbon\Carbon::now()->format('F d, Y') }}</p> <!-- Displays the current date -->
    </div>

    <!-- Report Title -->
    <h1>Feedback for Event: {{ $feedbacks->first()->event_name }}</h1>

    <!-- Table for Feedback Data -->
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>User Name</th>
                    <th>Feedback Text</th>
                    <th>Rating</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($feedbacks as $feedback)
                    <tr>
                        <td>{{ $feedback->user_name }}</td>
                        <td>{{ $feedback->feedback_text }}</td>
                        <td>{{ $feedback->rating }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Footer Section -->
    <div class="footer">
        <p>Generated by Church Management System - All rights reserved.</p>
    </div>

</body>
</html>
